# compose.yml
services:
    yt:
        build:
            context: .
            dockerfile: Dockerfile
        image: llama3_imagem_70b-ft:latest
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: 1
                          capabilities: [gpu]
        environment:
            - DISPLAY=:0
            - NVIDIA_DRIVER_CAPABILITIES=all
            - NVIDIA_VISIBLE_DEVICES=all
            - DEBUG_COLORS=1
            - TERM=xterm-256color
            - COLORTERM=truecolor
            - CHOKIDAR_USEPOLLING=true
        volumes:
            # isso aqui tá errado:
            #- ./data.py:/app/data.py
            # prefira usar:
            - ./app:/app:rw
            # faça cache dos models para evitar download ao limpar imagens:
            - ./data/huggingface_cache:/root/.cache/huggingface
            - ./data/pip_cache:/root/.cache/pip
        tty: true
        ipc: host
        ulimits:
            memlock: -1
            stack: 67108864
        shm_size: '8gb'
        stdin_open: true

        # precisa ativar o runtime nvidia no docker config (veja README.md)
        runtime: nvidia
